# Generated by Django 4.2.7 on 2025-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(default='abC', editable=False, max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tenant_id',
            field=models.UUIDField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant',
        ),
    ]
